[package]
name = "huffr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
evm-rs-emulator = "0.1.4"
huff_lexer = "0.3.0"
huff_utils = "0.1.0"
